# Generated by Django 3.2.1 on 2022-11-27 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20221126_1925'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todolist',
            table='todolist',
        ),
    ]
