# Generated by Django 3.2.1 on 2022-11-27 18:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_alter_todolist_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 11, 27, 18, 30, 54, 929524, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
